name: Lint and Build

on:
  pull_request:
    paths-ignore:
      - '.github/workflow/buildanddeploy.yml'
      - '.gitignore'
      - 'docs/**'
      - '*.md'
    branches:
      - 'main'

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: docker run --rm -v /tmp/runner/work/flourish-2023/flourish-2023:/tmp -w /tmp --entrypoint "/bin/sh" node:16-alpine -c "npm install && npm run lint"

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: docker run --rm -v /tmp/runner/work/flourish-2023/flourish-2023:/tmp -w /tmp --entrypoint "/bin/sh" node:16-alpine -c "npm install && npm run build"
